### ISSUE TITLE
Error 1054 SQL

### ISSUE THREAD

**Issue by gerardozamora1973** [JacksiroKe/q2a-blog-post#12]
> HP Question2Answer MySQL query error 1054: Unknown column 'blog' in 'where clause' - Query: 

`SELECT * \ r \ n \ t \ t \ t \ t \ tFROM qa_posts \ r \ n \ t \ t \ t \ t \ tWHERE postid <blog \ r \ n \ t \ t \ t \ t \ tAND type = 'Q' \ r \ n \ t \ t \ t \ t \ tORDER BY postid DESC \ r \ n \ t \ t \ t \ t \ tLIMIT 1, referer: http: // localhost / q2a / blog / write`

Help.

Tks

**Comment by JacksiroKe** [comment]
issue fixed in the latest update
