### ISSUE TITLE
 blog save error

### ISSUE THREAD

**Issue by gerardozamora1973** [JacksiroKe/q2a-blog-post#14]
AH01071: Got error 'PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/misite.com/httpdocs/qa-include/qa-base.php(720) : eval()'d code on line 86PHP message: PHP Question2Answer MySQL query error 1054: Unknown column 'blog' in 'where clause' - Query: SELECT * \n\t\t\t\t\tFROM qa_posts \n\t\t\t\t\tWHERE postid < blog\n\t\t\t\t\tAND type='Q'\n\t\t\t\t\tORDER BY postid DESC\n\t\t\t\t\tLIMIT 1'

Tks for you help

**Comment by JacksiroKe** [comment]
Hey @gerardozamora1973 I fixed the issues as you had outlined earlier. Kindly update from the last release

**Comment by gerardozamora1973** [comment]
Indeed it happens to me with your last version

Maybe it's compatibility issues with other plugins. I have almost 20 from various developers 

What tables do I have to delete?

Maybe it's also it ..

**Comment by JacksiroKe** [comment]
Well sorry for the inconvenience caused by the plugin. However I suspect you are not using the latest one that updated today morning. But then from the look of things its appears you may be having other plugins conflicting the whole Q2A system and since the plugins relies so much on that it keeps failing your site.

Kindly check my test site https://qtoa.appsmata.com/blog where you can sign up and and post on my blog.

Now to be able to find out what is the issue try to install a new Q2A site on your localhost following this instruction https://github.com/JacksiroKe/q2a-blog-post/blob/master/INSTALLING.md and see if it works well on your localhost. Then start adding other plugins to it and monitor the behavior of your site.

**Comment by gerardozamora1973** [comment]
Installing on a "clean" localhost works perfectly. I recognize this.

But on my production site it doesn't work.

Maybe you will remove the previous version and delete the previously generated tables will serve

Or maybe it's also the incompatibility with other plugins from other developers

I will test it and see how it works thanks for your help and time

Note in localhost with a previous version installed does not work what should be removed?

**Comment by JacksiroKe** [comment]
try to delete the tables
-  ``qa_blog_cats``
-  ``qa_blog_posts``
- ``qa_blog_users``

then also delete the blog folder from qa-plugins and try to do a clean install again

**Comment by gerardozamora1973** [comment]
Perform the procedure as mentioned and it was not possible at my production site.

AH01071: I received the error message 'PHP: PHP warning: count (): The parameter must be an array or an object that implements Accounting in /var/www/vhosts/tumundo.club/httpdocs/qa-include/qa- base.php (720): eval () 'd code on line 86 \ nPHP message: PHP2 question MySQL answer error 1054: unknown column' blog 'in' where clause '- Query: SELECT * \ n \ t \ t \ t \ t \ tFROM qa_posts \ n \ t \ t \ t \ t \ tWHERE postid <blog \ n \ t \ t \ t \ t \ tAND type = 'Q' \ n \ t \ t \ t \ t \ tORDER BY postid DESC \ n \ t \ t \ t \ t \ tLIMIT 1 \ n ', reference: https://misitio.com/blog/write

In a perfect clean install on localhost

Well in that I think that if my site is the one that is wrong

Thank you

**Comment by gerardozamora1973** [comment]
I made a bad solution.

Add Blog column in qa_posts table

And works

But just add the column with no parameters.

This will cause some problem? 

just add the ID column blog name

Well I think it was not the best solution.

Unable to add comments

Vote

or flagging

**Comment by gerardozamora1973** [comment]
Thanks. Good Day

**Comment by JacksiroKe** [comment]
comments, votes and flagging are all premium features
