### ISSUE TITLE
Blog Edit Not working

### ISSUE THREAD

**Issue by kmarsus** [JacksiroKe/q2a-blog-post#17]
Hi, 
Thanks for the nice plugin. But the blog edit button not working.

**Comment by MadCat34** [comment]
+1

**Comment by jacksiro254** [comment]
Sorry I will work on this now that am back to php development

**Comment by Ajinkgupta** [comment]
Thanks please jackshiro

**Comment by sujanbd** [comment]
edit, delete not working in latest version...please update.

**Comment by JacksiroKe** [comment]
Fixed in the latest commit
