### ISSUE TITLE
the site just went down

### ISSUE THREAD

**Issue by Kevin-woob** [JacksiroKe/q2a-blog-post#20]
had to remove the plugin, after installation the site just went down with error 500

**Comment by Ajinkgupta** [comment]
Have you find any solution

**Comment by Kevin-woob** [comment]
nope, i just removed the plugin and didnt use it

**Comment by Ajinkgupta** [comment]
ohk

**Comment by JacksiroKe** [comment]
I can't tell why your site went down but certainly its you who could find out in your logs why
